import { GeistSans } from "geist/font/sans"
import { LanguageProvider } from "@/components/language-context"
import SiteNav from "@/components/site-nav"
import "./globals.css"

export const metadata = {
  title: "Piramittek",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${GeistSans.className} bg-black text-white`}>
        <SiteNav />
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  )
}